services:
  newfitnet:
    image: ${DOCKER_REGISTRY-}newfitnet
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  postgres:
    image: postgres:14.3
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ./.containers/fitnet-db:/var/lib/postgresql/data 
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5   
  gotenberg:
    image: gotenberg/gotenberg:8
    ports:
      - "3000:3000"      